  
language: java
addons:
  sonarcloud:
    organization: "nikolapantelic-ftn"
    token: $SONARCLOUD_TOKEN
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE isa;'
script: 
    - cd server
    - mvn clean verify sonar:sonar -Pcoverage -Dsonar.projectKey=isa:project
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app:
    develop: isa-pharmacy

    
